# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: simulation.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'simulation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10simulation.proto\x12\nsimulation\"W\n\x16MatchPredictionRequest\x12\x11\n\thome_team\x18\x01 \x01(\t\x12\x11\n\taway_team\x18\x02 \x01(\t\x12\x17\n\x0ftournament_date\x18\x03 \x01(\t\"y\n\x17MatchPredictionResponse\x12\x15\n\rhome_win_prob\x18\x01 \x01(\x02\x12\x15\n\raway_win_prob\x18\x02 \x01(\x02\x12\x11\n\tdraw_prob\x18\x03 \x01(\x02\x12\x1d\n\x15underdog_signal_score\x18\x04 \x01(\x02\"O\n\x1bTournamentSimulationRequest\x12\x17\n\x0ftournament_year\x18\x01 \x01(\x05\x12\x17\n\x0fsimulation_runs\x18\x02 \x01(\x05\"J\n\x14SimulationTaskStatus\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x11\n\tredis_key\x18\x03 \x01(\t2\xcd\x01\n\x11SimulationService\x12W\n\x0cPredictMatch\x12\".simulation.MatchPredictionRequest\x1a#.simulation.MatchPredictionResponse\x12_\n\x12SimulateTournament\x12\'.simulation.TournamentSimulationRequest\x1a .simulation.SimulationTaskStatusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'simulation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MATCHPREDICTIONREQUEST']._serialized_start=32
  _globals['_MATCHPREDICTIONREQUEST']._serialized_end=119
  _globals['_MATCHPREDICTIONRESPONSE']._serialized_start=121
  _globals['_MATCHPREDICTIONRESPONSE']._serialized_end=242
  _globals['_TOURNAMENTSIMULATIONREQUEST']._serialized_start=244
  _globals['_TOURNAMENTSIMULATIONREQUEST']._serialized_end=323
  _globals['_SIMULATIONTASKSTATUS']._serialized_start=325
  _globals['_SIMULATIONTASKSTATUS']._serialized_end=399
  _globals['_SIMULATIONSERVICE']._serialized_start=402
  _globals['_SIMULATIONSERVICE']._serialized_end=607
# @@protoc_insertion_point(module_scope)
